sudo: required
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=budgetq
    - ORG=g0vhk

services:
  - docker

script:
    - npm install --only=dev
    - npm run lint
    - docker build -t $ORG/$REPO:$COMMIT .

after_success:
    - export TAG='latest'
    - docker tag $ORG/$REPO:$COMMIT $ORG/$REPO:$TAG
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $ORG/$REPO
